### ISSUE TITLE
ебал тебя слегка

### ISSUE THREAD

**Issue by ghost** [goodmind/sublime-flowstate#1]
Пидорас, сука
![ouxkoqscynu](https://cloud.githubusercontent.com/assets/9162638/12886022/a1bd883c-ce7b-11e5-90b6-96dcecfc8a82.jpg)

**Comment by wowse** [comment]
sas

**Comment by ghost** [comment]
@wowse ебало заткни на хуй. Сука, блять

**Comment by ghost** [comment]
@goodmind ты че, пидрила, закрыл иссуе?
